### ISSUE TITLE
Checkpoint 2 (or 3)

### ISSUE THREAD

**Issue by atharvalele** [atharvalele/ece585_final_project#7]
- Read input trace correctly
- Maintain simulation time
- Display current time
- Display info from the request(req time, R/W, Addr)
    - Topology for special impressions
    - ?? To be displayed whenever anything is inserted in queue?? 
- Display information kept in the queue
    - R/W, Address, ?Time in queue?
    - ?? Display when removed from the queue ??

- If there is nothing in the queue, its OK to go to the next request in the file

**Comment by doyleranpo** [comment]
Checkpoint 2 (3) implementation complete

- Addition to queue happens on CPU Clock Tick
- Eviction from queue happens at DRAM Cycle 
   - Each DRAM cycle is executed after every nth CPU cycle because CPU is faster than the memory
- (For Checkpoint 2 (3)) The eviction of the command takes place at 50 DRAM cycles = 100 Clock cycles

Tests Carried out 
- Multicore Test [PASS]
    - Tests include requests by different core at the same time 
    - If 2 requests arrive at the same time they are loaded in sequentially
    - (Checkpoint 2(3)) The eviction at 50 DRAM cycle depends on when the request was accepted into the queue
    - (Checkpoint 2(3)) Since eviction is a DRAM operation it can be observed that a few evictions aren't exactly at 50 DRAM cycles
    - (Checkpoint 2(3)) This is because requests are accepted at sequential CPU cycles, bur only evicted at every DRAM cycle which is every other CPU cycle
    - (Checkpoint 2(3))  This causes the delay in the expected time in queue because depending on when it was accepted the request can end up somewhere between 100 - 104 CPU clock cycles in the queue
    - (Checkpoint 2(3)) This is considered as a PASS because we understand the working and the 100 cycles is just a place holder  condition for the checkpoint

- Queue Overflow Test [PASS]
   - Queue upper limit = 16
   - Test includes 18 consecutive commands being given one after another 
   - This causes the queue to be full at the 16th command and produce a stall
   - A new command is not loaded onto the queue till one command has been completed execution [Evicted at 100 CPU cycles (Checkpoint 2(3))]
   - As soon as the queue has a spot empty the 17th command is loaded onto the queue
   - Same goes for the 18th command issued by the CPU

- Time Advancement Test [PASS}
   - Test runs commands with significant differences between issue times
   - Behavior of the simulator is as expected
   - If the queue is empty and the input trace file still has commands the time is advanced to the time given in the file

**Comment by atharvalele** [comment]
Okay perfect.
